server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8787/api/;
        proxy_read_timeout 120s;
        client_max_body_size 500M;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
