import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Lock, Zap, BarChart2 } from 'lucide-react';
import { useUpload } from '../hooks/useUpload';
import { setReportData } from '../store/reportStore';
import UploadBox from '../components/upload/UploadBox';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';
import Spinner from '../components/ui/Spinner';

export default function Upload() {
  const { state, upload } = useUpload();
  const navigate = useNavigate();

  useEffect(() => {
    if (state.status === 'done') {
      setReportData(state.data);   // store in memory — no size limit
      navigate('/report');
    }
  }, [state, navigate]);

  return (
    <div className="min-h-screen flex flex-col" style={{ background: 'var(--bg-base)' }}>
      <Header />
      <main className="flex-1 flex flex-col items-center justify-center px-4 py-16">
        <div className="w-full max-w-2xl space-y-8">
          <div className="text-center space-y-3">
            <h2 className="text-3xl font-bold" style={{ color: 'var(--text-primary)' }}>
              Analyse Performance Data
            </h2>
            <p className="text-base max-w-md mx-auto" style={{ color: 'var(--text-secondary)' }}>
              Upload a{' '}
              <code
                className="mono px-1 py-0.5 rounded"
                style={{ color: 'var(--accent)', background: 'var(--accent-subtle)' }}
              >
                .tar.gz
              </code>{' '}
              archive generated by the Linux AIO Performance Collector to get an interactive report.
            </p>
          </div>

          {state.status === 'uploading' ? (
            <div
              className="rounded-2xl p-12"
              style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }}
            >
              <Spinner label="Processing archive — this may take up to 60 seconds..." />
            </div>
          ) : (
            <div
              className="rounded-2xl p-6"
              style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }}
            >
              <UploadBox onFile={upload} />
            </div>
          )}

          {state.status === 'error' && (
            <div
              className="rounded-xl px-5 py-4 text-sm"
              style={{
                background: 'rgba(220, 38, 38, 0.1)',
                border: '1px solid rgba(220, 38, 38, 0.4)',
                color: 'var(--status-error)',
              }}
            >
              <span className="font-semibold">Error: </span>{state.message}
            </div>
          )}

          <div className="grid grid-cols-3 gap-4 text-center">
            {[
              { icon: <Lock size={22} />,    title: 'Private',       desc: 'Data processed in memory, deleted after use' },
              { icon: <Zap size={22} />,     title: 'Fast',          desc: 'Interactive charts, no page reloads' },
              { icon: <BarChart2 size={22} />, title: 'Comprehensive', desc: 'CPU, disk, memory, network, processes' },
            ].map(({ icon, title, desc }) => (
              <div
                key={title}
                className="rounded-xl p-4"
                style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }}
              >
                <div className="flex justify-center mb-2" style={{ color: 'var(--accent)' }}>{icon}</div>
                <div className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>{title}</div>
                <div className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>{desc}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
