import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useUpload } from '../hooks/useUpload';
import UploadBox from '../components/upload/UploadBox';
import Header from '../components/layout/Header';
import Spinner from '../components/ui/Spinner';

export default function Upload() {
  const { state, upload } = useUpload();
  const navigate = useNavigate();

  useEffect(() => {
    if (state.status === 'done') {
      navigate('/report', { state: { data: state.data } });
    }
  }, [state, navigate]);

  return (
    <div className="min-h-screen flex flex-col bg-[#0f1117]">
      <Header />
      <main className="flex-1 flex flex-col items-center justify-center px-4 py-16">
        <div className="w-full max-w-2xl space-y-8">
          <div className="text-center space-y-3">
            <h2 className="text-3xl font-bold text-slate-100">
              Analyse Performance Data
            </h2>
            <p className="text-slate-400 text-base max-w-md mx-auto">
              Upload a <code className="mono text-indigo-400 bg-indigo-950/40 px-1 py-0.5 rounded">.tar.gz</code> archive
              generated by the Linux AIO Performance Collector to get an interactive report.
            </p>
          </div>

          {state.status === 'uploading' ? (
            <div className="bg-[#1a1d27] border border-[#2d3149] rounded-2xl p-12">
              <Spinner label="Processing archive — this may take up to 60 seconds..." />
            </div>
          ) : (
            <div className="bg-[#1a1d27] border border-[#2d3149] rounded-2xl p-6">
              <UploadBox onFile={upload} />
            </div>
          )}

          {state.status === 'error' && (
            <div className="bg-red-950/40 border border-red-800/60 rounded-xl px-5 py-4 text-red-300 text-sm">
              <span className="font-semibold">Error: </span>{state.message}
            </div>
          )}

          <div className="grid grid-cols-3 gap-4 text-center">
            {[
              { icon: '🔒', title: 'Private', desc: 'Data processed in memory, deleted after use' },
              { icon: '⚡', title: 'Fast', desc: 'Interactive charts, no page reloads' },
              { icon: '📊', title: 'Comprehensive', desc: 'CPU, disk, memory, network, processes' },
            ].map(({ icon, title, desc }) => (
              <div key={title} className="bg-[#1a1d27] border border-[#2d3149] rounded-xl p-4">
                <div className="text-2xl mb-2">{icon}</div>
                <div className="text-sm font-semibold text-slate-200">{title}</div>
                <div className="text-xs text-slate-500 mt-1">{desc}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
